baseURL = 'https://limesroeien.nl/'
languageCode = 'nl-NL'
title = 'Roeivereniging Limes'
theme = 'hugo-flex'

[params]
color = "#A7321B"
footer = ""

[menu]
main = [
  { name = "Home", pageRef = "/", weight = 1},
  { name = "Contact", pageRef = "/contact", weight = 2 },
  { name = "Aanmelden", pageRef = "/aanmelden", weight = 3 },
  { name = "FAQ", pageRef = "/faq", weight = 4 },
  { name = "Leden", pageRef="/leden", weight = 5 }
]

