baseURL = 'https://limesroeien.nl/'
languageCode = 'nl-NL'
title = 'Roeivereniging Limes'
theme = 'hugo-flex'

[params]
showdate = false
css = ["css/custom.css"]
color = "#a52217"
footer = ""
description = 'Roeivereniging Limes is een hechte en groeiende roeiclub in Bunnik/Odijk/Werkhoven en omgeving. Ontdek het prachtige roeiwater van de Kromme Rijn. Kom proefroeien!'
keywords = "roeien, roei club, odijk, bunnik, leren roeien"

[menu]
main = [
  { name = "Home", pageRef = "/", weight = 1},
  { name = "Over ons", pageRef = "/over", weight = 2 },
  { name = "FAQ", pageRef = "/faq", weight = 3 },
  { name = "Roeien", pageRef = "/roeien", weight = 4 },
  { name = "Contact", pageRef = "/contact", weight = 5 },
]

